using System.Collections.Generic;
using Ring.Simulation.Core;
using Unity.Mathematics;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using Ring.Presentation;

namespace Ring.Editor
{
    /// bd `app-w4ca` (spec §3.5): the baker. It takes the poses the five bodies
    /// are actually drawn in off their clips and writes them into data the
    /// simulation can read — one `.posetable` per skeleton.
    ///
    /// ⛔ IT IS A BOOTSTRAP, NOT AN IMPORTER, and that is the project's own
    /// convention: data is generated by idempotent commands under `Ring/…`, and
    /// running it twice leaves the tree untouched (R-IDEM). The
    /// `ScriptedImporter` beside it does NOT bake — it only brings the artifact
    /// into the asset database and holds the dependency on the source `.fbx`.
    ///
    /// ⛔⛔ FIVE ARTIFACTS, NOT ONE, BECAUSE THERE ARE FIVE RIGS: George, Leela,
    /// Trilobite, QuadShell and the UAL2 mannequin carry 47 / 17 / 20 / 28 / 65
    /// skinning bones. One table indexed by archetype would have to pad to the
    /// widest, and a bone index would stop meaning the same thing in two rows.
    ///
    /// ⛔⛔ THE TABLE CARRIES BODY BONES ONLY (decision Р-A of this task). The
    /// table stores POSITIONS WITHOUT NAMES, while "is this a body bone" is a
    /// question about the NAME — so a table holding fingers and IK targets
    /// could not answer its own `GatherRadius` afterwards, and the number would
    /// need either a seventh field on `PoseTable` (whose shape is pinned at
    /// six) or a sidecar file (a second home). Dropping them costs nothing that
    /// is read: no hit volume hangs on a knuckle — eleven volumes for the
    /// collector and not one of them on a finger — while the gunner's
    /// `PoleTarget.L` travels 6.42 m from his own axis in the death clip.
    ///
    /// ⛔⛔ THE CLIP ORDER IS A CONTRACT, NOT AN ACCIDENT:
    ///   clip 0            — THE REST CLIP (`AnimatorCatalog.IdleClipOf`), so
    ///                       ROW 0 IS THE REST POSE and validation rule 13 has
    ///                       a row to compare `RestBottom`/`RestTop` against;
    ///   clip 1            — THE SLIDE LOOP where the body has one, so
    ///                       validation rule 16 can ask for the slide's crown
    ///                       at all. A table carries no clip NAMES, so "which
    ///                       row is the slide" has to be a POSITION;
    ///                       `SimConfigBuilder.SlideClipIndex` and
    ///                       `TestConfigs.SlideClipIndex` are the two readers
    ///                       of this half of the contract, and the rule stands
    ///                       down on a body whose table never reached clip 1
    ///                       (every mob);
    ///   the LAST clip     — death / shutdown, so "every row except the last
    ///                       clip's" is exactly the set `GatherRadius` is taken
    ///                       over (Р559: the gather circle includes the hit
    ///                       reactions, because a body playing one can still be
    ///                       shot, and excludes the death take, because a
    ///                       falling body sweeps its bones far from its axis
    ///                       and nobody can be hit during it);
    ///   in between        — sorted by take name, ordinal, so the order does
    ///                       not depend on how the controller happens to
    ///                       enumerate its states.
    ///
    /// ⛔ SAMPLING RATE IS TWO NUMBERS, AND THE CHOICE IS MEASURED (COMBAT-001
    /// §3.8): linear interpolation error at 30 Hz is about 1.45 cm at a 30 cm
    /// radius for a limb turning at ~20000 deg/s^2, and 0.36 cm at 60 Hz; calm
    /// locomotion at 30 Hz costs 0.15 cm. ⇒ locomotion and rest bake at 30 Hz,
    /// the fast takes — reactions, melee, shots, the slide's entry and exit —
    /// at 60.
    public static class PoseBaker
    {
        const string PosesDir = "Assets/Data/Poses";

        const int SlowRateHz = 30;
        const int FastRateHz = 60;

        /// Death and shutdown takes. ⚠ The Sci-Fi kit calls it `TurnOff` — a
        /// robot powering down IS that pack's death take (`AnimIds`' own doc).
        static readonly string[] DeathTakes = { "Death01", "Death", "TurnOff" };

        /// The take that becomes clip 1 — the slide's steady state, which is
        /// the pose validation rule 16 measures the collector's crown in.
        /// ⚠ Taken from the catalog rather than spelled again here.
        static readonly string SlideLoopTake =
            AnimatorCatalog.PackClipOf(AnimIds.SlideLoopName);

        /// Takes that bake at 60 Hz: the ones whose limbs turn fast enough for
        /// the 30 Hz error above to matter.
        static readonly string[] FastTakes =
        {
            "Hit_Chest", "Hit_Head", "HitRecieve_1", "HitRecieve_2", "Hit",
            "Punch", "Shoot", "Attack", "AttackAuto", "Pistol_Shoot",
            "Slide_Start", "Slide_Exit",
        };

        [MenuItem("Ring/Bootstrap/Pose Table")]
        public static void Bake()
        {
            var report = new System.Text.StringBuilder();
            report.AppendLine("=== POSE BAKE (bd app-w4ca, spec 3.5) ===");

            EditorBootstrapUtils.EnsureFolder(PosesDir);

            foreach (AnimatorCatalog.BodyEntry body in AnimatorCatalog.Bodies)
            {
                var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(body.PrefabPath);
                if (prefab == null)
                    throw new System.ArgumentException(
                        $"{body.Kind}: prefab missing at {body.PrefabPath} — a body that cannot be "
                        + "baked would ship an empty pose table, which is a body nothing can hit");

                PoseTable table = BakeOne(prefab);
                string path = $"{PosesDir}/{body.Kind}.posetable";
                PoseTableImporter.Write(path, table);
                ReportOne(report, body, prefab, in table);
            }

            AssetDatabase.Refresh();
            Debug.Log(report.ToString());
        }

        /// ONE body, and NOTHING WRITTEN TO DISK — this shape is a requirement
        /// of two callers, not a convenience. The "rebake and compare" gate
        /// holds a fresh bake beside the committed artifact, and fixture 28
        /// pins the measure origin; without it both would have to write to a
        /// temp directory and read back, which measures the serializer too.
        public static PoseTable BakeOne(GameObject prefab)
        {
            GameObject instance = Object.Instantiate(prefab);
            try
            {
                instance.transform.position = Vector3.zero;
                instance.transform.rotation = Quaternion.identity;

                // ⛔ BODY BONES ONLY (decision Р-A above). The index of a bone
                // HERE is its column in every row of the table.
                var bones = new List<Transform>();
                foreach (Transform b in PoseSampling.CollectBones(instance))
                    if (PoseSampling.IsBodyBone(b.name)) bones.Add(b);
                if (bones.Count == 0)
                    throw new System.ArgumentException(
                        $"{prefab.name}: no body bones — nothing to bake");

                Animator animator = instance.GetComponentInChildren<Animator>(true);
                List<AnimationClip> clips = BakeSet(animator);
                if (clips.Count == 0)
                    throw new System.ArgumentException(
                        $"{prefab.name}: its controller reaches no clip this body can be baked "
                        + "from — an empty table is an unhittable body (rule 12)");

                // Row plan first, so the arrays are allocated once.
                var firstRow = new int[clips.Count + 1];
                for (int c = 0; c < clips.Count; c++)
                {
                    firstRow[c + 1] = firstRow[c] + RowsOf(clips[c]);
                }
                int rows = firstRow[clips.Count];

                var table = new PoseTable
                {
                    BoneCount = bones.Count,
                    ClipFirstRow = firstRow,
                    Bones = new float3[rows * bones.Count],
                    BlendThresholds = ReadBlendThresholds(animator),
                    UpperLayerMask = ReadUpperLayerMask(animator, bones),
                    Checksum = 0UL,
                };

                var row = new float3[bones.Count];
                GameObject sampleTarget = animator != null ? animator.gameObject : instance;
                AnimationMode.StartAnimationMode();
                try
                {
                    for (int c = 0; c < clips.Count; c++)
                    {
                        AnimationClip clip = clips[c];
                        int n = firstRow[c + 1] - firstRow[c];
                        float rate = RateOf(clip);
                        for (int r = 0; r < n; r++)
                        {
                            float t = math.min(r / rate, clip.length);
                            PoseSampling.SamplePose(sampleTarget, instance.transform,
                                bones, clip, t, row);
                            System.Array.Copy(row, 0, table.Bones,
                                (firstRow[c] + r) * bones.Count, bones.Count);
                        }
                    }
                }
                finally
                {
                    AnimationMode.StopAnimationMode();
                }

                // ⛔ THE CHECKSUM IS THE SAME FOLD THE CONFIG BUILD RECOMPUTES
                // (`SimConfigHash.PoseTableChecksum`), never a second spelling
                // of it — otherwise validation rule 27 would compare two
                // implementations rather than the numbers.
                table.Checksum = SimConfigHash.PoseTableChecksum(in table);
                return table;
            }
            finally
            {
                Object.DestroyImmediate(instance);
            }
        }

        /// THE BONE-AXIS REACH of a baked table: the furthest any bone gets
        /// from the body's own vertical axis, over every row EXCEPT the last
        /// clip's — the death take, by the ordering contract above.
        ///
        /// ⚠ THIS IS NOT `GatherRadius` AND MUST NOT BE MISTAKEN FOR IT. It is
        /// the figure `SkeletonAudit` prints as COMBAT REACH, and the auditor's
        /// own wording says why: it is the reach "BEFORE the volume's own
        /// radius is added". The gather circle has to cover the VOLUMES, which
        /// is `HitParts.GatherReach(parts, table)` — that one takes each part's
        /// radius with it, and validation rule 9 is written against it. This
        /// member exists so the bake report can be held beside the auditor's
        /// number and the two compared; on the five shipped bodies they agree
        /// to 2-3 mm, the cost of 32 phases per clip against 30/60 Hz.
        public static float BoneAxisReachOf(in PoseTable t)
        {
            int rowStride = t.BoneCount;
            int allRows = t.Bones.Length / rowStride;
            // Every row up to the last clip's first row; a single-clip table
            // has no death take to exclude and measures all of itself.
            int last = t.ClipFirstRow.Length >= 2
                ? t.ClipFirstRow[t.ClipFirstRow.Length - 2]
                : allRows;
            if (last <= 0) last = allRows;

            float widest = 0f;
            for (int r = 0; r < last; r++)
            {
                for (int b = 0; b < rowStride; b++)
                {
                    float3 p = t.Bones[r * rowStride + b];
                    float reach = math.sqrt(p.x * p.x + p.z * p.z);
                    if (reach > widest) widest = reach;
                }
            }
            return widest;
        }

        // ---- what gets baked ------------------------------------------------

        /// The bake set: the reach filter PLUS death/shutdown, ordered by the
        /// contract in this class's doc.
        ///
        /// ⛔ WIDER THAN THE REACH FILTER ON PURPOSE (spec §3.5): the pose of a
        /// DEAD body is read by `PersistentPropsDirector` for the heights it
        /// spawns debris at, so the death take has to be IN the table — while
        /// staying OUT of the `GatherRadius` maximum.
        static List<AnimationClip> BakeSet(Animator animator)
        {
            var set = new List<AnimationClip>();
            if (animator == null) return set;

            AnimationClip rest = AnimatorCatalog.IdleClipOf(animator);
            AnimationClip slide = null;
            var middle = new List<AnimationClip>();
            var death = new List<AnimationClip>();

            foreach (AnimationClip c in PoseSampling.CollectClips(animator))
            {
                if (c == rest) continue;
                if (IsDeathTake(c.name)) { death.Add(c); continue; }
                if (!SkeletonAudit.IsCombatClip(c.name)) continue;
                if (slide == null && AnimatorCatalog.TakeOf(c.name) == SlideLoopTake) slide = c;
                else middle.Add(c);
            }

            middle.Sort((a, b) => string.CompareOrdinal(
                AnimatorCatalog.TakeOf(a.name), AnimatorCatalog.TakeOf(b.name)));
            death.Sort((a, b) => string.CompareOrdinal(
                AnimatorCatalog.TakeOf(a.name), AnimatorCatalog.TakeOf(b.name)));

            // ⛔⛔ THE ORDER CONTRACT IS CHECKED, NOT MERELY BUILT (found by the
            // code-review round of this task). Three validation rules stand on
            // it, and every way it can fail fails SILENTLY:
            //   * NO death take at all ⇒ the last clip is an ordinary combat
            //     one, and `GatherReach` would drop a LIVE animation from the
            //     gather circle — the exact silent miss rule 9 exists to stop;
            //   * TWO death takes ⇒ only the last is excluded, and the other
            //     INFLATES the circle by the very sweep the exclusion is for;
            //   * no slide loop on a body rule 16 judges ⇒ clip 1 is some other
            //     clip, and rule 16 measures a crown that is not the slide's.
            if (death.Count != 1)
                throw new System.ArgumentException(
                    $"{animator.gameObject.name}: expected exactly one death take, found "
                    + $"{death.Count} — the clip-order contract puts the death take LAST so that "
                    + "the gather radius can exclude it, and neither zero nor two can be ordered "
                    + $"that way (takes recognised as death: {string.Join(", ", DeathTakes)})");

            set.Add(rest);
            if (slide != null) set.Add(slide);
            set.AddRange(middle);
            set.AddRange(death);
            return set;
        }

        static bool IsDeathTake(string clipName)
        {
            string take = AnimatorCatalog.TakeOf(clipName);
            for (int i = 0; i < DeathTakes.Length; i++)
                if (take == DeathTakes[i]) return true;
            return false;
        }

        static float RateOf(AnimationClip clip)
        {
            string take = AnimatorCatalog.TakeOf(clip.name);
            for (int i = 0; i < FastTakes.Length; i++)
                if (take == FastTakes[i]) return FastRateHz;
            return SlowRateHz;
        }

        /// ⚠ AT LEAST ONE ROW, ALWAYS: a clip shorter than one sample still has
        /// a pose, and a zero-row clip would make `ClipFirstRow` ambiguous
        /// (two clips starting at the same row).
        static int RowsOf(AnimationClip clip) =>
            math.max(1, (int)math.ceil(clip.length * RateOf(clip)));

        // ---- the two arrays beside the rows ---------------------------------

        /// The locomotion blend tree's thresholds, READ FROM THE CONTROLLER.
        ///
        /// ⛔ FROM THE ASSET, NOT FROM THE BOOTSTRAP'S LITERALS (Р564): the
        /// bootstrap returns early for an existing controller and never
        /// reconciles thresholds, so its four numbers are a SEED and the
        /// committed controller is the live home. And they travel in the table
        /// because the tree's weight is computed in `Ring.Simulation`, from
        /// which this file is not visible at all.
        ///
        /// ⚠ MOBS HAVE NO BLEND TREE: an empty array, which is their build
        /// rather than an omission.
        static float[] ReadBlendThresholds(Animator animator)
        {
            var controller = animator == null
                ? null
                : animator.runtimeAnimatorController as AnimatorController;
            if (controller == null || controller.layers.Length == 0)
                return System.Array.Empty<float>();

            foreach (ChildAnimatorState child in controller.layers[0].stateMachine.states)
            {
                var tree = child.state == null ? null : child.state.motion as BlendTree;
                if (tree == null) continue;
                ChildMotion[] children = tree.children;
                var thresholds = new float[children.Length];
                for (int i = 0; i < children.Length; i++) thresholds[i] = children[i].threshold;
                return thresholds;
            }
            return System.Array.Empty<float>();
        }

        /// ⛔⛔ THE AIM LAYER'S MASK, ONE BIT PER BAKED BONE (spec §3.6). Six of
        /// the collector's eleven volumes take their pose from the aim layer
        /// and five from locomotion, so a resolver that does not know which is
        /// which cannot compose the two layers at all.
        ///
        /// ⛔ IT IS BAKED FROM THE `AvatarMask` THE BOOTSTRAP CREATED, never
        /// from a list of bone names written out here: the mask is humanoid
        /// BODY PARTS, the bootstrap sets each of the thirteen explicitly, and
        /// a copy of that decision in this file would drift from the asset
        /// silently.
        ///
        /// ⚠ MOBS HAVE ONE LAYER ⇒ an all-zero mask, and that is their build.
        static ulong[] ReadUpperLayerMask(Animator animator, List<Transform> bones)
        {
            var mask = new ulong[(bones.Count + 63) / 64];

            var controller = animator == null
                ? null
                : animator.runtimeAnimatorController as AnimatorController;
            if (controller == null) return mask;

            AvatarMask avatarMask = null;
            foreach (AnimatorControllerLayer layer in controller.layers)
                if (layer.name == AnimIds.AimLayerName && layer.avatarMask != null)
                    avatarMask = layer.avatarMask;
            if (avatarMask == null) return mask;

            Avatar avatar = animator.avatar;
            if (avatar == null || !avatar.isHuman) return mask;

            // Which transform IS which humanoid bone, asked once.
            var humanOf = new Dictionary<Transform, HumanBodyBones>();
            for (int i = 0; i < (int)HumanBodyBones.LastBone; i++)
            {
                Transform t = animator.GetBoneTransform((HumanBodyBones)i);
                if (t != null && !humanOf.ContainsKey(t)) humanOf[t] = (HumanBodyBones)i;
            }

            for (int b = 0; b < bones.Count; b++)
            {
                // A baked bone may be a twist or leaf bone the humanoid rig
                // does not name; it belongs to the nearest named ancestor.
                Transform walk = bones[b];
                while (walk != null && !humanOf.ContainsKey(walk)) walk = walk.parent;
                if (walk == null) continue;

                if (!avatarMask.GetHumanoidBodyPartActive(PartOf(humanOf[walk]))) continue;
                mask[b / 64] |= 1UL << (b % 64);
            }
            return mask;
        }

        /// Which mask body part a humanoid bone belongs to. ⛔ Unity exposes the
        /// mask BY PART and the rig BY BONE and offers no mapping between them,
        /// so it is written out here — once, beside the only reader.
        static AvatarMaskBodyPart PartOf(HumanBodyBones bone)
        {
            switch (bone)
            {
                case HumanBodyBones.Hips:
                case HumanBodyBones.Spine:
                case HumanBodyBones.Chest:
                case HumanBodyBones.UpperChest:
                    return AvatarMaskBodyPart.Body;

                case HumanBodyBones.Neck:
                case HumanBodyBones.Head:
                case HumanBodyBones.LeftEye:
                case HumanBodyBones.RightEye:
                case HumanBodyBones.Jaw:
                    return AvatarMaskBodyPart.Head;

                case HumanBodyBones.LeftUpperLeg:
                case HumanBodyBones.LeftLowerLeg:
                case HumanBodyBones.LeftFoot:
                case HumanBodyBones.LeftToes:
                    return AvatarMaskBodyPart.LeftLeg;

                case HumanBodyBones.RightUpperLeg:
                case HumanBodyBones.RightLowerLeg:
                case HumanBodyBones.RightFoot:
                case HumanBodyBones.RightToes:
                    return AvatarMaskBodyPart.RightLeg;

                case HumanBodyBones.LeftShoulder:
                case HumanBodyBones.LeftUpperArm:
                case HumanBodyBones.LeftLowerArm:
                case HumanBodyBones.LeftHand:
                    return AvatarMaskBodyPart.LeftArm;

                case HumanBodyBones.RightShoulder:
                case HumanBodyBones.RightUpperArm:
                case HumanBodyBones.RightLowerArm:
                case HumanBodyBones.RightHand:
                    return AvatarMaskBodyPart.RightArm;

                default:
                    // Every remaining humanoid bone is a finger, and the two
                    // finger parts are all that is left to tell apart.
                    return bone >= HumanBodyBones.RightThumbProximal
                        ? AvatarMaskBodyPart.RightFingers
                        : AvatarMaskBodyPart.LeftFingers;
            }
        }

        // ---- the report ------------------------------------------------------

        /// ⛔ THE MINIMUM HEAD LEVER OVER EVERY PHASE IS A DoD ITEM (spec §4.4,
        /// test 34a), not a nicety: if a head volume collapses onto the body
        /// axis in some phase, the outcome quietly changes in that phase only,
        /// and nothing else in the pipeline would report it.
        static void ReportOne(System.Text.StringBuilder report, AnimatorCatalog.BodyEntry body,
            GameObject prefab, in PoseTable t)
        {
            int stride = t.BoneCount;
            int rows = t.Bones.Length / stride;
            int bytes = t.Bones.Length * 12;

            report.AppendLine();
            report.AppendLine($"########## {body.Kind} — {body.PrefabPath}");
            report.AppendLine(
                $"  bones {stride}, clips {t.ClipFirstRow.Length - 1}, rows {rows}, "
                + $"{bytes / 1024f:F1} KB, thresholds {t.BlendThresholds.Length}, "
                + $"aim-layer bones {MaskBits(t.UpperLayerMask)}, "
                + $"checksum 0x{t.Checksum:X16}");
            report.AppendLine("  BONE-AXIS REACH (rows outside the death take, before the "
                + $"volume radius): {BoneAxisReachOf(in t):F3} m");

            int head = HeadBoneIndex(prefab, stride);
            if (head < 0)
            {
                report.AppendLine("  HEAD LEVER: no head bone on this rig");
                return;
            }
            float min = float.MaxValue, max = 0f;
            for (int r = 0; r < rows; r++)
            {
                float3 p = t.Bones[r * stride + head];
                float lever = math.sqrt(p.x * p.x + p.z * p.z);
                if (lever < min) min = lever;
                if (lever > max) max = lever;
            }
            report.AppendLine(
                $"  ⭐ HEAD LEVER over all {rows} phases: min {min:F4} m, max {max:F4} m");
        }

        static int MaskBits(ulong[] mask)
        {
            int n = 0;
            for (int i = 0; i < mask.Length; i++) n += math.countbits(mask[i]);
            return n;
        }

        /// The head bone's column, by the same name test the rig itself uses.
        /// ⚠ Instantiated again rather than kept from the bake: this runs once
        /// per body, off the report path, and holding the instance alive across
        /// the write would be a longer-lived object for a shorter reason.
        static int HeadBoneIndex(GameObject prefab, int expectedCount)
        {
            GameObject instance = Object.Instantiate(prefab);
            try
            {
                var bones = new List<Transform>();
                foreach (Transform b in PoseSampling.CollectBones(instance))
                    if (PoseSampling.IsBodyBone(b.name)) bones.Add(b);
                if (bones.Count != expectedCount) return -1;
                for (int i = 0; i < bones.Count; i++)
                    if (bones[i].name.ToLowerInvariant().Contains("head")) return i;
                return -1;
            }
            finally
            {
                Object.DestroyImmediate(instance);
            }
        }
    }
}
